### ISSUE TITLE
Runcoderun doesn't use exemplor's color output

### ISSUE THREAD

**Issue by agrimm** [quackingduck-archive/exemplor#8]
According to http://support.runcoderun.com/discussions/questions/54-does-runcoderun-support-color , runcoderun supports color, but currently exemplor doesn't display in color (eg http://runcoderun.com/agrimm/exemplor/builds/c8ef82ed02cb11162586d1f22ed003e51f5bc8ee/1/ruby_191 )

**Comment by quackingduck** [comment]
does this work in the latest version?

**Comment by agrimm** [comment]
I'll have a look at this some time, but you could add a runcoderun post-commit hook to your own github repository.

**Comment by quackingduck** [comment]
I could. But seeing as your already doing it .... :)

**Comment by agrimm** [comment]
Since you asked nicely!

**Comment by agrimm** [comment]
Is the latest version of exemplor version 2000.2.0 from November 3?

**Comment by agrimm** [comment]
Currently not in color, unless there's updates you haven't pushed to github: http://runcoderun.com/agrimm/exemplor/builds/2da83db802dead2ff257b158de826fce59b9ba71/1/ruby_186

**Comment by quackingduck** [comment]
Oops. I had release the new version (2010, written at railscamp) without pushing the code. It's pushed now. And I now know why the output isn't in color: because the stdout stream of the script that runs `rake test` (I assume) on runcoderun is not a tty.

One way to fix this would be to add a `--color` option to exemplor that forces color and then use that in `rake test`. Honestly, I'm not excited about runcoderun to do this myself. I just run the tests before I commit.

**Comment by agrimm** [comment]
I might create an experimental branch doing that and see if that's the problem. I'm not sure if it is, because I can't see color being forced in the micronaut example mentioned in the runcoderun support forum (then again, maybe the rakefile is too complicated for me to understand). 

However, if it turns out that it's a matter of adding a --color option, are you ok with the feature being added so long as you don't have to do it?

Incidentally, do you ever forget to add files to a commit? (That's the #1 cause of me breaking the build)

**Comment by quackingduck** [comment]
It's definitely the problem. Because with 2010 you get distinctly different output depending on whether stdout is a tty. When it is: fancy colors and unicode chars like ✓; when it isn't: yaml.

I would definitely include a --color option.

I do sometimes forget. Are you talking about any files in particular?

**Comment by agrimm** [comment]
I'm not talking about any files in particular. Just mentioning why I sometimes benefit from continuous integration, rather than running the tests in my work directory.

**Comment by agrimm** [comment]
Hmm. RCR-related bugs are somewhat moot now.
